<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('pim_packages', function (Blueprint $table): void {
            $table->increments('id');

            // Stable ID generated by the backoffice — upsert key for /api/admin/* sync.
            // Nullable for shop-bootstrap rows without a backoffice counterpart.
            $table->unsignedBigInteger('backoffice_id')->nullable()->unique();

            // Unique slug — identity used by the shop (standard/premium/vip)
            $table->string('slug', 50)->unique();

            // Display data
            $table->string('name', 100);
            $table->string('tagline', 255)->nullable();
            $table->text('description')->nullable();

            // Prices stored as unsigned integers (grosze) — never float for money.
            // Box prices default to these but can override per-box.
            $table->unsignedInteger('price_pln');
            $table->unsignedInteger('price_eur')->nullable();
            $table->unsignedInteger('price_usd')->nullable();

            // UI flags
            $table->boolean('highlighted')->default(false);  // the "most popular" tier
            $table->unsignedSmallInteger('sort_order')->default(0);
            $table->boolean('active')->default(true);  // backoffice can hide without deleting

            $table->timestamps();

            $table->index(['active', 'sort_order']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('pim_packages');
    }
};
